apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-app
spec:
  selector:
    matchLabels:
      app: registration-app
  replicas: 1
  template:
    metadata:
      labels:
        app: registration-app
    spec:
      containers:
        - name: registration-service
          image: dockeroo80/uima-registration-service
          ports:
            - containerPort: 80
          env:
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: registration-service-secrets
                  key: rabbitmq-password
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: registration-service-secrets
                  key: rabbitmq-username
            - name: Bugsnag__ApiKey
              valueFrom:
                secretKeyRef:
                  name: registration-service-secrets
                  key: bugsnag-api-key
            - name: ConnectionStrings__Users
              valueFrom:
                secretKeyRef:
                  name: registration-service-secrets
                  key: users-connection-strings
            - name: Jabber__Host
              valueFrom:
                configMapKeyRef:
                  name: registration-service-configs
                  key: jabber-host
            - name: RabbitMQ__Exchange
              valueFrom:
                configMapKeyRef:
                  name: registration-service-configs
                  key: rabbitmq-exchange
            - name: RabbitMQ__Host
              valueFrom:
                configMapKeyRef:
                  name: registration-service-configs
                  key: rabbitmq-host
